# Project metadata
group=me.totalfreedom
version=26.11
pluginName=TotalFreedomMod
javaVersion=25

buildAuthor=TotalFreedom
buildCodeName=Acamar

# Gradle configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

netbeans.hint.jdkPlatform=JDK_temurin-25.0.3_from_X__.jdks_temurin-25.0.3
